### ISSUE TITLE
Fatal error: Class 'WHMCS_Cookie' not found shows when a user applies Coupon 

### ISSUE THREAD

**Issue by artaweb** [tripflex/whmcs-affcoupons#41]
When I activated debuging, I got this error:

 `Fatal error: Class 'WHMCS_Cookie' not found in /home/username/public_html/modules/addons/affcoupons/hooks.php on line 48`

**Comment by ninjasaga** [comment]
Same Here! Anyone get solutions for this issue?

**Comment by artaweb** [comment]
nah. I am waiting for this.

**Comment by willihangga** [comment]
is there any solution yet? I'm facing the same problem with this module version

**Comment by InstantWeb** [comment]
I used the newest update and get this error:

modules/addons/affcoupons/hooks.php:48
Stack trace:
#0 /home/instabill/public_html/includes/hookfunctions.php(0): affcoupons_set_affiliate_cookie(Array)
#1 /home/instabill/public_html/includes/orderfunctions.php(0): run_hook('PreCalculateCar...', Array)
#2 /home/instabill/public_html/cart.php(0): calcCartTotals(false, false, Array)
#3 {main}
